<?xml version="1.0" encoding="UTF-8"?><testrun name="HibernateUtilTest (1)" project="Processos" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="br.com.fasete.processos.util.HibernateUtilTest" time="0.326">
    <testcase name="conectar" classname="br.com.fasete.processos.util.HibernateUtilTest" time="0.326">
      <error>java.lang.ExceptionInInitializerError&#13;
	at br.com.fasete.processos.util.HibernateUtil.criarFabricaDeSessoes(HibernateUtil.java:27)&#13;
	at br.com.fasete.processos.util.HibernateUtil.&lt;clinit&gt;(HibernateUtil.java:11)&#13;
	at br.com.fasete.processos.util.HibernateUtilTest.conectar(HibernateUtilTest.java:10)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: org.hibernate.MappingException: Unable to load class [ br.com.fasete.processos.basicas.Usuario] declared in Hibernate configuration &lt;mapping/&gt; entry&#13;
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2281)&#13;
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)&#13;
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)&#13;
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)&#13;
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)&#13;
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)&#13;
	at br.com.fasete.processos.util.HibernateUtil.criarFabricaDeSessoes(HibernateUtil.java:19)&#13;
	... 25 more&#13;
Caused by: java.lang.ClassNotFoundException: br.com.fasete.processos.basicas.Usuario&#13;
	at java.net.URLClassLoader.findClass(Unknown Source)&#13;
	at java.lang.ClassLoader.loadClass(Unknown Source)&#13;
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)&#13;
	at java.lang.ClassLoader.loadClass(Unknown Source)&#13;
	at java.lang.Class.forName0(Native Method)&#13;
	at java.lang.Class.forName(Unknown Source)&#13;
	at org.hibernate.internal.util.ReflectHelper.classForName(ReflectHelper.java:193)&#13;
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2278)&#13;
	... 31 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
